[tool.poetry]
name = "gentoogram-bot"
version = "0.3.1"
description = ""
authors = ["Lee Watson <me@lwatson.dev>"]
license = "GPL-3.0"

[tool.poetry.dependencies]
python = "^3.11"
python-telegram-bot = "^20.0"
sentry-sdk = "^1.5.0"
dynaconf = { extras = ["yaml"], version = "^3.1.2" }

[tool.poetry.group.dev.dependencies]
black = "^22.1.0"
pre-commit = "^2.16.0"
flake8 = "^4.0.1"
isort = "^5.9.1"
pyupgrade = "^3.3.1"

[tool.isort]
profile = "black"
src_paths = ["gentoogram"]

[build-system]
requires = ["poetry>=1.3.0"]
build-backend = "poetry.core.masonry.api"
