[project]
name = "gentoogram-bot"
description = ""
authors = [{ name = "Lee Watson", email = "<me@lwatson.dev>" }]
version = "0.8.5"
readme = "README.md"
license = { file = "LICENSE" }
requires-python = ">=3.13"
dynamic = ["dependencies"]

[tool.poetry]
package-mode = false
requires-poetry = ">=2.0"

[tool.poetry.dependencies]
sentry-sdk = "^2.8.0"
dynaconf = { extras = ["yaml"], version = "^3.2.4" }
python-telegram-bot = { version = "^21.0.1", extras = ["webhooks"] }

[tool.poetry.group.dev.dependencies]
pre-commit = "^4.0.0"
pre-commit-hooks = "^5.0.0"
ruff = "^0.9.0"
shellcheck-py = "^0.10.0.1"

[tool.ruff]
force-exclude = true

[tool.ruff.lint]
select = [
    "A",
    "ARG",
    "B",
    "BLE",
    "C4",
    "C90",
    "DTZ",
    "E",
    "ERA",
    "F",
    "FIX",
    "FURB",
    "I",
    "N",
    "PL",
    "PTH",
    "Q",
    "RET",
    "RSE",
    "RUF",
    "S",
    "SIM",
    "SLF",
    "T10",
    "T20",
    "TID",
    "UP",
    "W",
    "YTT",
]

# ruff format compatibility
ignore = ["E501"]

extend-ignore = ["PLR09"]

[tool.ruff.format]
line-ending = "lf"

[build-system]
requires = ["poetry-core>=2.0"]
build-backend = "poetry.core.masonry.api"
