[tool.poetry]
name = "gentoogram-bot"
version = "0.8.4"
description = ""
authors = ["Lee Watson <me@lwatson.dev>"]
license = "GPL-3.0"
package-mode = false

[tool.poetry.dependencies]
python = "^3.12"
sentry-sdk = "^1.43.0"
dynaconf = { extras = ["yaml"], version = "^3.2.4" }
python-telegram-bot = { version = "^21.0.1", extras = ["webhooks"] }

[tool.poetry.group.dev.dependencies]
pre-commit = "^3.5.0"
pre-commit-hooks = "^4.5.0"
ruff = "^0.5.0"
shellcheck-py = "^0.10.0.1"

[tool.ruff]
target-version = "py312"
force-exclude = true

[tool.ruff.lint]
select = [
    "A",
    "ARG",
    "B",
    "BLE",
    "C4",
    "C90",
    "DTZ",
    "E",
    "ERA",
    "F",
    "FIX",
    # "FURB",
    "I",
    "N",
    "PL",
    "PTH",
    "Q",
    "RET",
    "RSE",
    "RUF",
    "S",
    "SIM",
    "SLF",
    "T10",
    "T20",
    "TID",
    "UP",
    "W",
    "YTT",
]

# ruff format compatibility
ignore = ["E501"]

extend-ignore = ["PLR09"]

[tool.ruff.format]
line-ending = "lf"

[build-system]
requires = ["poetry>=1.3.0"]
build-backend = "poetry.core.masonry.api"
