[tool.poetry]
name = "gentoogram-bot"
version = "0.1.0"
description = ""
authors = ["Lee Watson <rev@revthefox.co.uk>"]
license = "GPL-3.0"

[tool.poetry.dependencies]
python = "^3.8"
python-telegram-bot = "^13.0"
sentry-sdk = "^1.0.0"
requests = "^2.25.0"
dynaconf = {extras = ["yaml"], version = "^3.1.2"}

[tool.poetry.dev-dependencies]
black = "^20.8b1"
flake8 = "^3.9.0"
pre-commit = "^2.11.1"

[build-system]
requires = ["poetry>=1.0"]
build-backend = "poetry.masonry.api"
