[tool.poetry]
name = "gentoogram-bot"
version = "0.2.7"
description = ""
authors = ["Lee Watson <me@lwatson.dev>"]
license = "GPL-3.0"

[tool.poetry.dependencies]
python = "^3.9"
python-telegram-bot = "^13.0"
sentry-sdk = "^1.5.0"
requests = "^2.25.0"
dynaconf = {extras = ["yaml"], version = "^3.1.2"}

[tool.poetry.dev-dependencies]
black = "^22.1.0"
pre-commit = "^2.16.0"
flake8 = "^4.0.1"
isort = "^5.9.1"

[tool.isort]
profile = "black"
src_paths = ["gentoogram"]

[build-system]
requires = ["poetry>=1.0"]
build-backend = "poetry.masonry.api"
