[tool.poetry]
name = "gentoogram-bot"
version = "0.4.0"
description = ""
authors = ["Lee Watson <me@lwatson.dev>"]
license = "GPL-3.0"

[tool.poetry.dependencies]
python = "^3.11"
sentry-sdk = "^1.5.0"
dynaconf = { extras = ["yaml"], version = "^3.1.2" }
python-telegram-bot = {version = "^20.1", extras = ["webhooks"]}

[tool.poetry.group.dev.dependencies]
pre-commit = "^3.5.0"
pre-commit-hooks = "^4.5.0"
ruff = "^0.1.1"

[tool.ruff]
target-version = "py311"
force-exclude = true

select = [
    "A",
    "B",
    "BLE",
    "C90",
    "E",
    "ERA",
    "F",
    "FIX",
    "I",
    "N",
    "PTH",
    "RET",
    "RSE",
    "RUF",
    "S",
    "SIM",
    "T20",
    "UP",
    "W",
    "YTT",
]

# ruff format compatibility
extend-ignore = [
    "E501",
    "W191",
]

[build-system]
requires = ["poetry>=1.3.0"]
build-backend = "poetry.core.masonry.api"
