[tool.poetry]
name = "gentoogram-bot"
version = "0.4.0"
description = ""
authors = ["Lee Watson <me@lwatson.dev>"]
license = "GPL-3.0"

[tool.poetry.dependencies]
python = "^3.11"
sentry-sdk = "^1.5.0"
dynaconf = { extras = ["yaml"], version = "^3.1.2" }
python-telegram-bot = {version = "^20.1", extras = ["webhooks"]}

[tool.poetry.group.dev.dependencies]
black = "^23.10.0"
pre-commit = "^3.5.0"
pre-commit-hooks = "^4.5.0"
ruff = "^0.1.1"

[tool.ruff]
target-version = "py311"
force-exclude = true

select = [
    "B", "I", "UP", "C90", "W",
    "YTT", "PTH", "A", "RET", "SIM",
    "FIX", "ERA", "Q", "T20", "RUF",
    "S", "RSE", "BLE", "N", "E",
    "F",
]

[build-system]
requires = ["poetry>=1.3.0"]
build-backend = "poetry.core.masonry.api"
