[tool.poetry]
name = "gentoogram-bot"
version = "0.1.0"
description = ""
authors = ["Lee Watson <rev@revthefox.co.uk>"]
license = "GPL-3.0"

[tool.poetry.dependencies]
python = "^3.6"
python-telegram-bot = "^12.1"
dynaconf = "^2.1"
sentry-sdk = "^0.13.4"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
