telegram:
  token: ''
  chat_id: -1234

# Regex filters
filters:
  # Users with usernames matching any of these will be kicked from the group and their join message will be deleted.
  usernames: []
  messages: []

sentry:
  dsn: ''

# Telegram user ids.
admins: []

logging:
  version: 1
  root:
    level: INFO
    handlers: [console]
  formatters:
    console:
      format: '[%(asctime)s] [%(levelname)-5s] %(message)s'
  handlers:
    console:
      class: logging.StreamHandler
      formatter: console
      stream: ext://sys.stdout
