telegram:
  token:
  chat_id:
  admin_id:

## https://github.com/python-telegram-bot/python-telegram-bot/wiki/Webhooks
# webhook:
#   enabled: false
#   listen: "0.0.0.0"
#   port: 3020
#   url_base: "https://example.com"
#   url_path: "/"

# filters:
#   usernames: []
#   messages: []

# sentry:
#   dsn: ""

# cas:
#   enabled: true
#   threshold: 1
